import Head from 'next/head'
import { About } from '../components/about/About.component'
import { Banner } from '../components/banner/Banner.component'
import { Devis } from '../components/devis/devis.component'
import { Footer } from '../components/footer/Footer.compoent'
import { Form } from '../components/form/Form.component'
import { Info } from '../components/info/Info.component'
import { Service } from '../components/services/Service.component'
import { Topbar } from '../shared/Topbar/Topbar.component'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Topbar/>
        <Banner/>
        <Form/>
        <About/>
        <Service/>
        <Devis/>
        <Info/>
        <Footer/>
      </main>
    </div>
  )
}
